version: '3.5'
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=start
    volumes:
      - ./mariadb:/var/lib/mysql
    ports:
      - 3306:3306
  backend:
    build: ./backend
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./backend/app:/app
  frontend:
    build: ./frontend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./frontend/app/src
        target: /app/src